jobs--montages--create:
  handler: modules/montages__create/run.run
  events:
    - schedule:
        rate: cron(0 16 * * ? *)

jobs--streams--analyze:
  handler: modules/streams__analyze/run.run
  events:
    - schedule:
        rate: cron(0 15 * * ? *)

